<?php
$Commentary   = "// This file has been automatically generated by Radio Record Stations Builder\n";
$Commentary  .= "// Date: " . date("Y.m.d") . "\n";
$Commentary  .= "// Time: " . date("H:i:s") . "\n\n";

function GetBestItem($List, $BestItems, $IfItemNotExists = '') {
  foreach ($BestItems as $Item)
    if (isset($List[$Item]))
      return $List[$Item];

  return $IfItemNotExists;
}

$JSON = json_decode(file_get_contents("http://www.radiorecord.ru/radioapi/stations/"), true);
$File = "\"Stations\"\n{\n";

foreach ($JSON['result'] as $Station) {
  $Name = $Station['title'];
  $URL  = GetBestItem($Station, ['stream_320', 'stream_256', 'stream_128', 'stream_64', 'stream_32', 'stream'], '');
  $File .= "\t\"{$Name}\"\t\t\"{$URL}\"\n";
}

$File .= "}\n";

file_put_contents('Radio.cfg', $Commentary . $File);